#!/usr/bin/env bash
# bash script that Configure my Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server;/a rewrite ^/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
