#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" >> /etc/nginx/sites-available/default
sudo /etc/init.d/nginx start
