#!/usr/bin/env bash
# Script That add header x server to ngiunx config
sudo apt update
sudo apt install nginx
sudo sed -i "17i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
