#!/usr/bin/env bash
#Bash script that gives you information about the school file
FILE=/holberton-system_engineering-devops/0x04-loops_conditions_and_parsing/school
if test -f "$FILE";
then
	echo "school file exists"
else 
	echo "school file does not exist"
fi
if [ -s school ];
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ ! -f "$FILE"  ];
then
	echo "school is a regular file"
fi
