#!/usr/bin/env bash
#Bash script that configures nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
chown nginx:nginx /etc/nginx/nginx.conf
chmod ugo+rwx /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
